import { Inter } from "next/font/google";
// import "./globals.css";
import "@/resources/sass/styles.scss";
import Navbar from "@/components/Navbar";
import Providers from "./provider";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />

          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
