import { Inter } from "next/font/google";
// import "./globals.css";
import "@/resources/sass/styles.scss";

import Providers from "./provider";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Hello, World!</title>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
